In [57]:
import pandas as pd
import os

pd.options.display.float_format = '{:1.2f}'.format
pd.options.display.max_columns = None

In [ ]:
files = 0
for file in os.listdir("raw_listing"):
    files += 1
print(f"Number of listing files: {files}")

Number of listing files: 27

In [59]:
df = pd.read_csv(f"raw_listing/CRMLSListing202502.csv", encoding='latin-1')

print('listing data:')
df.head()

listing data:

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,PropertyType.1,MlsStatus,ElementarySchool,ListAgentFirstName.1,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,Longitude.1,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,Latitude.1,ListPrice.1,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,ListAgentLastName.1,CloseDate.1,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1100000.00,1108426966,Andrew.Liberty@compass.com,NaN,NaN,Andrew R.,Liberty,34.11,-118.25,3170 Larga Avenue,ResidentialIncome,1196.00,1100000.00,29,Compass,NaN,"Secret HQ, Inc",Andrew R. Liberty,Lek,Adjchavanich,NaN,NaN,NaN,NaN,NaN,NaN,1108426966,606 - Atwater,NaN,Los Angeles,ResidentialIncome,Active,NaN,Andrew R.,False,0.00,NaN,NaN,0.12,NaN,NaN,1928.00,29,3170.00,1196.00,25508805,2.00,Los Angeles,NaN,1196.00,2.00,2025-02-07,-118.25,NaN,NaN,NaN,2025-02-07,NaN,NaN,34.11,1100000.00,CA,NaN,NaN,NaN,NaN,NaN,MultiSplit,Liberty,NaN,NaN,5413.00,NaN,False,NaN,NaN,90039,NaN,NaN,5413.00,NaN,3170 Larga Avenue
1,595500.00,1108426965,williamramsey760@gmail.com,NaN,NaN,William,Ramsey,34.18,-116.07,72772 Nandina Street,Residential,1712.00,595500.00,0,"Sharon Rose Realty, Inc.",NaN,"Sharon Rose Realty, Inc.",William Ramsey,Luis,Carrillo,NaN,NaN,NaN,NaN,NaN,NaN,1108426965,DC710 - Desert Heights,NaN,San Bernardino,Residential,Active,NaN,William,True,2.00,NaN,SingleFamilyResidence,2.27,Not Applicable-1,NaN,2006.00,0,72772.00,1712.00,219126159PS,2.00,29 Palms,NaN,NaN,3.00,2025-02-25,-116.07,NaN,NaN,NaN,2025-02-25,NaN,NaN,34.18,595500.00,CA,NaN,NaN,True,1.00,NaN,One,Ramsey,NaN,NaN,99011.00,NaN,False,2.00,NaN,92277,NaN,NaN,99011.00,NaN,72772 Nandina Street
2,3500.00,1108426536,omegafunding@yahoo.com,NaN,NaN,Vartan,Missirian,34.13,-117.91,300 N San Gabriel Avenue,ResidentialLease,1380.00,3500.00,0,Legend Realtors,NaN,Legend Realtors,Vartan Missirian,Alina,Missirian,NaN,NaN,NaN,NaN,NaN,NaN,1108426536,607 - Azusa,NaN,Los Angeles,ResidentialLease,Active,NaN,Vartan,NaN,1.00,NaN,Duplex,6900.00,Not Applicable,NaN,1989.00,0,300.00,1380.00,P1-21172,2.00,Azusa,NaN,NaN,3.00,2025-02-27,-117.91,NaN,NaN,NaN,2025-02-27,NaN,NaN,34.13,3500.00,CA,NaN,NaN,True,1.00,NaN,One,Missirian,NaN,NaN,6900.00,3.00,NaN,0.00,NaN,91702,NaN,0.00,300564000.00,NaN,300 N San Gabriel Avenue
3,995000.00,1108426334,Jessica@native.us,NaN,NaN,Jessica,Foote,33.61,-117.19,26891 Aubrieta Street,Residential,3863.00,995000.00,0,Native,NaN,Native,Jessica Foote,Reanne,Mosley,NaN,NaN,NaN,NaN,Monthly,NaN,1108426334,SRCAR - Southwest Riverside County,NaN,Riverside,Residential,Active,NaN,Jessica,True,6.00,NaN,SingleFamilyResidence,0.16,NaN,NaN,2005.00,0,26891.00,3863.00,SW25044469,5.00,Murrieta,NaN,NaN,4.00,2025-02-26,-117.19,NaN,NaN,NaN,2025-02-26,NaN,NaN,33.61,995000.00,CA,NaN,NaN,True,2.00,NaN,Two,Foote,NaN,NaN,6970.00,1.00,False,4.00,Murrieta,92562,NaN,227.00,6970.00,NaN,26891 Aubrieta Street
4,1485000.00,1108425215,nickiwanderson@gmail.com,NaN,NaN,Nicki,Anderson,35.14,-120.56,608 Stagecoach,Residential,2411.00,1485000.00,0,Comet Realty,NaN,Comet Realty,Nicki Anderson,Brian,Gust,NaN,NaN,NaN,NaN,Monthly,NaN,1108425215,AG-East of Hwy 101,NaN,San Luis Obispo,Residential,Active,Branch,Nicki,True,3.00,Midland Pacific,SingleFamilyResidence,0.47,NaN,NaN,2001.00,0,608.00,2411.00,PI25050653,3.00,Arroyo Grande,NaN,NaN,3.00,2025-02-27,-120.56,NaN,NaN,NaN,2025-02-27,NaN,NaN,35.14,1485000.00,CA,NaN,NaN,True,NaN,NaN,MultiSplit,Anderson,NaN,NaN,0.47,1.00,False,3.00,Lucia Mar Unified,93420,NaN,72.00,20473.20,NaN,608 Stagecoach

In [5]:
df.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'StreetNumberNumeric', 'LivingArea.1', 'ListingId',
       'BathroomsTotalInteger', 'City', 'TaxYear', 'BuildingAreaTotal',
       'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [58]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,Longitude.1,ElementarySchoolDistrict,BelowGradeFinishedArea,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,38978.00,39095.00,2358.00,38479.00,38495.00,34264.00,39029.00,39095.00,0.00,0.00,39095.00,323.00,36826.00,35563.00,35988.00,39095.00,38911.00,34264.00,35979.00,38.00,6426.00,34356.00,38495.00,0.00,178.00,38479.00,39029.00,0.00,28460.00,35739.00,17648.00,31672.00,26741.00,35684.00,0.00
mean,1108713.76,1155316467.85,707837.04,34.68,-118.54,1951.38,1065802.91,8.31,NaN,NaN,1155316467.85,246164.32,3.10,57.91,1979.17,8.31,33876.98,1951.38,2.56,2024.32,3507.31,3.19,-118.54,NaN,93.25,34.68,1065802.91,NaN,1.37,80353.64,1.90,1.74,226.95,520195.47,NaN
std,4681781.44,670122.94,1708757.52,1.74,4.27,1628.26,2128495.72,10.17,NaN,NaN,670122.94,4142260.07,59.50,4562.87,28.36,10.17,1039082.19,1628.26,1.90,3.16,11528.36,1.88,4.27,NaN,335.22,1.74,2128495.72,NaN,0.48,3801159.82,1.40,3.41,601.19,18389379.18,NaN
min,0.70,1139626731.00,0.00,0.00,-124.20,0.00,0.00,0.00,NaN,NaN,1139626731.00,0.00,-7.00,0.00,1800.00,0.00,0.00,0.00,0.00,2010.00,0.00,0.00,-124.20,NaN,0.00,0.00,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,189000.00,1154866557.50,3500.00,33.76,-118.78,1194.00,189900.00,1.00,NaN,NaN,1154866557.50,506.01,1.00,0.12,1960.00,1.00,800.00,1194.00,2.00,2025.00,1258.25,2.00,-118.78,NaN,0.00,33.76,189900.00,NaN,1.00,4997.00,1.00,1.00,0.00,5300.00,NaN
50%,680000.00,1155378587.00,6800.00,34.07,-118.17,1626.00,680000.00,7.00,NaN,NaN,1155378587.00,8940.00,2.00,0.17,1980.00,7.00,2836.00,1626.00,2.00,2025.00,1936.00,3.00,-118.17,NaN,0.00,34.07,680000.00,NaN,1.00,7290.00,2.00,2.00,0.00,7512.00,NaN
75%,1250000.00,1155789714.50,965000.00,34.54,-117.31,2286.25,1249888.00,13.00,NaN,NaN,1155789714.50,19375.00,3.00,0.41,2002.00,13.00,10790.00,2286.25,3.00,2025.00,3369.00,4.00,-117.31,NaN,0.00,34.54,1249888.00,NaN,2.00,14484.50,3.00,2.00,352.50,17840.00,NaN
max,569950000.00,1156721382.00,47000000.00,81.00,118.20,99999.00,88000000.00,434.00,NaN,NaN,1156721382.00,74460000.00,10522.00,618036.00,2027.00,434.00,68719500.00,99999.00,64.00,2026.00,392040.00,59.00,118.20,NaN,3000.00,81.00,88000000.00,NaN,2.00,574992247.00,33.00,400.00,39600.00,2106169560.00,NaN

In [49]:
#choose data timeline to merge together for analysis
start_year = 2024
start_month = 1
end_year = 2026
end_month = 3

if start_year < 2024 or start_year > 2026 or end_year < 2024 or end_year > 2026:
    raise ValueError("Invalid year value")

if start_month < 1 or start_month > 12 or end_month < 1 or end_month > 12:
    raise ValueError("Invalid month value")

index_start = (start_year - 2024) * 12 + start_month - 1
index_times = (end_year - start_year) * 12 + end_month - start_month

if index_start < 0 or index_times < 0:
    raise ValueError("Invalid start or end date")

print(f"merging {index_times + 1} files")

merged_df = None
folder_path = "raw_listing"
for i, file in enumerate(os.listdir(folder_path)):
    if i < index_start or i > index_start + index_times:
        continue
    df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
    if merged_df is None:
        merged_df = df
    else:
        merged_df = pd.concat([merged_df, df])

merging 27 files

In [50]:
merged_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,830397.00,833632.00,228127.00,722001.00,722697.00,729907.00,831554.00,833632.00,0.00,0.00,...,722001.00,831554.00,0.00,617461.00,757546.00,385886.00,675846.00,564127.00,756497.00,0.00
mean,1048896.82,1103867004.41,781516.28,34.52,-118.36,3188.30,983068.62,19.16,NaN,NaN,...,34.52,983068.62,NaN,1.37,66356.84,1.93,1.76,204.74,567448.82,NaN
std,6334638.33,29389828.09,3490519.25,1.89,3.91,1064269.33,2162263.36,29.06,NaN,NaN,...,1.89,2162263.36,NaN,0.48,2383026.68,5.66,3.95,2084.44,23230248.10,NaN
min,0.00,421654881.00,0.00,-117.47,-159.52,0.00,0.00,-58.00,NaN,NaN,...,-117.47,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,85000.00,1077313378.75,5000.00,33.76,-118.52,1182.00,85000.00,4.00,NaN,NaN,...,33.76,85000.00,NaN,1.00,4931.00,1.00,1.00,0.00,5227.00,NaN
50%,639900.00,1103555092.50,565000.00,34.05,-118.09,1602.00,635000.00,10.00,NaN,NaN,...,34.05,635000.00,NaN,1.00,7220.00,2.00,2.00,0.00,7499.00,NaN
75%,1150000.00,1120230513.25,1024000.00,34.30,-117.29,2236.00,1150000.00,22.00,NaN,NaN,...,34.30,1150000.00,NaN,2.00,13626.00,3.00,2.00,310.00,16553.00,NaN
max,1390000000.00,1156721382.00,820000000.00,737.00,392.00,909090909.00,443650265.00,2539.00,NaN,NaN,...,737.00,443650265.00,NaN,2.00,918742280.00,3333.00,600.00,968348.00,7638115320.00,NaN