In [1]:
import pandas as pd
import os

In [ ]:
files = 0
for file in os.listdir("raw_sold"):
    files += 1
print(f"Number of sold files: {files}")

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_19172\3206727038.py:4: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"raw/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_19172\3206727038.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"raw/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_19172\3206727038.py:4: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"raw/{file}", encoding='latin-1')

Number of sold files: 27

In [ ]:
df_S = pd.read_csv(f"raw_sold/CRMLSSold202502.csv", encoding='latin-1')

print('sold data:')
df_S.head()

sold data:

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,RanchoSoutheast,RanchoSoutheast,NaN,True,NaN,NaN,NaN,60000.0,526199946,cmark1018@yahoo.com,...,NaN,28000.0,NaN,False,NaN,NaN,92307,0.0,28000.0,NaN
1,InlandValleys,InlandValleys,NaN,False,NaN,NaN,NaN,550000.0,525585060,mozcorona@aol.com,...,NaN,39640.0,NaN,False,NaN,NaN,92553,0.0,39640.0,NaN
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,880000.0,497696903,lenskab@gmail.com,...,NaN,NaN,NaN,False,2.0,NaN,91942,NaN,NaN,NaN
3,SanDiego,SanDiego,NaN,False,NaN,NaN,False,875000.0,497696407,lenskab@gmail.com,...,NaN,NaN,NaN,False,2.0,NaN,91942,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,849000.0,486616176,lenskab@gmail.com,...,NaN,NaN,NaN,False,2.0,NaN,91942,NaN,NaN,NaN

In [54]:
df_S.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict'],
      dtype='object')

In [55]:
df_S.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,1.864900e+04,1.870200e+04,1.870200e+04,18696.000000,18697.000000,17369.000000,1.867000e+04,18702.000000,0.0,0.0,...,0.0,79.000000,0.0,14675.000000,1.696300e+04,9732.000000,16123.000000,12758.000000,1.694800e+04,0.0
mean,9.834095e+05,1.096710e+09,8.383509e+05,34.547551,-118.479460,1806.417669,8.350316e+05,47.209069,NaN,NaN,...,NaN,116.139241,NaN,1.361635,3.785182e+04,1.923757,1.745426,198.773783,4.780565e+05,NaN
std,1.129628e+07,1.867204e+07,1.460342e+06,1.622960,3.351314,1116.065735,1.247063e+06,76.342037,NaN,NaN,...,NaN,710.055898,NaN,0.480490,6.069355e+05,1.439116,3.349437,594.613555,1.888928e+07,NaN
min,0.000000e+00,4.216536e+08,0.000000e+00,0.000000,-123.808907,0.000000,3.500000e+02,-288.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,1.399500e+04,1.093799e+09,1.256250e+04,33.740450,-118.558248,1179.000000,1.386250e+04,8.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,4.811000e+03,1.000000,1.000000,0.000000,5.097000e+03,NaN
50%,6.174710e+05,1.100883e+09,6.100000e+05,34.037131,-118.055650,1576.000000,6.071190e+05,22.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,7.020000e+03,2.000000,2.000000,0.000000,7.264500e+03,NaN
75%,1.075000e+06,1.102986e+09,1.068000e+06,34.369583,-117.331239,2140.000000,1.050000e+06,63.000000,NaN,NaN,...,NaN,0.000000,NaN,2.000000,1.170000e+04,3.000000,2.000000,305.000000,1.287000e+04,NaN
max,1.390000e+09,1.108121e+09,1.138117e+08,41.643482,117.298290,44194.000000,3.999500e+07,2799.000000,NaN,NaN,...,NaN,6104.000000,NaN,2.000000,6.730000e+07,32.000000,400.000000,46356.200000,1.821592e+09,NaN