In [1]:
import pandas as pd
import os

pd.options.display.float_format = '{:1.2f}'.format
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
files = 0
for file in os.listdir("raw_sold"):
    files += 1
print(f"Number of sold files: {files}")

Number of sold files: 27

In [3]:
df = pd.read_csv(f"raw_sold/CRMLSSold202502.csv", encoding='latin-1')

print('sold data:')
df.head()

sold data:

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,MlsStatus,ElementarySchool,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,RanchoSoutheast,RanchoSoutheast,NaN,True,NaN,NaN,NaN,60000.00,526199946,cmark1018@yahoo.com,2025-02-21,35000.00,Chris,Mark,34.54,-117.27,0 Quantico Road,Land,NaN,35000.00,196,Far West Realty,KW Vision,NaN,Chris Mark,NaN,NaN,TRSUDAJAM,James,Sudarsono,NaN,NaN,NaN,526199946,APPV - Apple Valley,NaN,San Bernardino,Closed,NaN,NaN,NaN,NaN,NaN,0.64,NaN,TriCounties,NaN,0.00,RS21140713,NaN,Apple Valley,NaN,NaN,NaN,2025-02-21,NaN,NaN,2022-01-10,2021-06-28,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28000.00,NaN,False,NaN,NaN,92307,0.00,28000.00,NaN
1,InlandValleys,InlandValleys,NaN,False,NaN,NaN,NaN,550000.00,525585060,mozcorona@aol.com,2025-02-14,625000.00,MANUEL,ZAMORANO,33.94,-117.24,24255 Sunnymead Boulevard,Land,NaN,550000.00,1232,"KAREN PIERCE, BROKER","KAREN PIERCE, BROKER",NaN,MANUEL ZAMORANO,NaN,NaN,ivzamoman,MANUEL,ZAMORANO,NaN,NaN,NaN,525585060,259 - Moreno Valley,NaN,Riverside,Closed,NaN,NaN,NaN,NaN,NaN,0.91,NaN,InlandValleys,NaN,24255.00,IV21138689,NaN,Moreno Valley,NaN,NaN,NaN,2025-02-14,NaN,NaN,2024-11-08,2021-06-25,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39640.00,NaN,False,NaN,NaN,92553,0.00,39640.00,NaN
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,880000.00,497696903,lenskab@gmail.com,2025-02-11,875000.00,Lenska,Bracknell,32.77,-117.04,4750 Dana Dr,Residential,2340.00,880000.00,20,LENSKA Realty,Coldwell Banker West,NaN,Lenska Bracknell,NaN,NaN,809976,Sheetal,Gandhi,NaN,NaN,NaN,497696903,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,6.00,NaN,SingleFamilyResidence,NaN,La Mesa,PacificSouthwest,2021.00,4750.00,210000201,4.00,La Mesa,NaN,NaN,4.00,2025-02-11,NaN,NaN,2021-01-25,2021-01-05,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN
3,SanDiego,SanDiego,NaN,False,NaN,NaN,False,875000.00,497696407,lenskab@gmail.com,2025-02-14,875000.00,Lenska,Bracknell,32.77,-117.04,4740 Dana Dr,Residential,2165.00,875000.00,9,LENSKA Realty,LENSKA Realty,NaN,Lenska Bracknell,NaN,NaN,SAND-649841,Lenska,Bracknell,NaN,NaN,NaN,497696407,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,4.00,NaN,SingleFamilyResidence,NaN,La Mesa,SanDiego,2021.00,4740.00,210000200,4.00,La Mesa,NaN,NaN,5.00,2025-02-14,NaN,NaN,2021-01-14,2021-01-05,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,849000.00,486616176,lenskab@gmail.com,2025-02-18,849000.00,Lenska,Bracknell,32.77,-117.04,4730 Dana Dr,Residential,2158.00,849000.00,91,LENSKA Realty,Heritage Homes San Diego,NaN,Lenska Bracknell,NaN,NaN,SAND-693007,Jason,Piske,NaN,NaN,NaN,486616176,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,4.00,NaN,SingleFamilyResidence,NaN,La Mesa,SanDiego,2021.00,4730.00,200049530,3.00,La Mesa,NaN,NaN,4.00,2025-02-18,NaN,NaN,2021-01-25,2020-10-22,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN

In [4]:
df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict'],
      dtype='object')

In [5]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,18649.00,18702.00,18702.00,18696.00,18697.00,17369.00,18670.00,18702.00,0.00,0.00,18702.00,95.00,18094.00,16908.00,17876.00,18651.00,17820.00,11.00,2637.00,17432.00,0.00,79.00,0.00,14675.00,16963.00,9732.00,16123.00,12758.00,16948.00,0.00
mean,983409.52,1096709782.05,838350.89,34.55,-118.48,1806.42,835031.62,47.21,NaN,NaN,1096709782.05,11431.70,2.39,48.26,1978.40,18863.77,2.46,2021.91,2611.76,3.07,NaN,116.14,NaN,1.36,37851.82,1.92,1.75,198.77,478056.46,NaN
std,11296281.99,18672040.17,1460341.89,1.62,3.35,1116.07,1247063.04,76.34,NaN,NaN,18672040.17,14804.16,4.29,2875.39,27.28,651982.38,1.41,4.01,4239.67,1.40,NaN,710.06,NaN,0.48,606935.47,1.44,3.35,594.61,18889275.45,NaN
min,0.00,421653552.00,0.00,0.00,-123.81,0.00,350.00,-288.00,NaN,NaN,421653552.00,0.00,-3.00,0.00,1776.00,0.00,0.00,2010.00,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,13995.00,1093798834.50,12562.50,33.74,-118.56,1179.00,13862.50,8.00,NaN,NaN,1093798834.50,270.00,2.00,0.12,1960.00,816.00,2.00,2023.00,1196.00,2.00,NaN,0.00,NaN,1.00,4811.00,1.00,1.00,0.00,5097.00,NaN
50%,617471.00,1100882618.50,610000.00,34.04,-118.06,1576.00,607119.00,22.00,NaN,NaN,1100882618.50,4638.00,2.00,0.17,1979.00,2812.00,2.00,2023.00,1740.00,3.00,NaN,0.00,NaN,1.00,7020.00,2.00,2.00,0.00,7264.50,NaN
75%,1075000.00,1102985592.75,1068000.00,34.37,-117.33,2140.00,1050000.00,63.00,NaN,NaN,1102985592.75,19932.50,2.00,0.30,2000.00,10760.00,3.00,2023.00,2726.00,4.00,NaN,0.00,NaN,2.00,11700.00,3.00,2.00,305.00,12870.00,NaN
max,1390000000.00,1108121032.00,113811672.00,41.64,117.30,44194.00,39995000.00,2799.00,NaN,NaN,1108121032.00,65787.00,400.00,287060.00,2025.00,60119213.00,61.00,2025.00,113471.00,61.00,NaN,6104.00,NaN,2.00,67300000.00,32.00,400.00,46356.20,1821592080.00,NaN

In [6]:
merged_df = None
folder_path = "raw_sold"
for file in os.listdir(folder_path):
    df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
    Residential_df = df[df['PropertyType'] == 'Residential']
    if merged_df is None:
        merged_df = df
        merged_residential_df = Residential_df
    else:
        merged_df = pd.concat([merged_df, df])
        merged_residential_df = pd.concat([merged_residential_df, Residential_df])

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23868\429532400.py:4: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23868\429532400.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23868\429532400.py:4: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')

In [7]:
merged_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,569460.00,571143.00,571136.00,552326.00,552486.00,530848.00,570264.00,571143.00,0.00,0.00,571143.00,2448.00,553086.00,516842.00,547122.00,569725.00,544675.00,352.00,74001.00,533115.00,0.00,2496.00,0.00,456407.00,518645.00,302751.00,498017.00,393422.00,518206.00,0.00,67780.00
mean,906836.19,1094110481.94,874306.98,34.53,-118.45,3555.48,839420.19,42.91,NaN,NaN,1094110481.94,18627.27,7.78,789.76,1978.06,20019.65,2.45,2022.91,2550.23,3.08,NaN,106.04,NaN,1.37,48530.76,1.93,1.77,184.91,469447.75,NaN,194.41
std,5837289.32,32286578.85,5289874.38,1.62,3.12,1247951.44,1276600.91,69.56,NaN,NaN,32286578.85,213045.25,3498.72,515219.62,27.08,1484660.29,1.42,2.45,5216.97,1.40,NaN,801.67,NaN,0.48,2275941.99,6.36,3.90,1661.86,20794580.68,NaN,2152.72
min,0.00,421449042.00,0.00,-117.47,-177.65,0.00,0.00,-288.00,NaN,NaN,421449042.00,0.00,-143.00,0.00,1776.00,0.00,0.00,2009.00,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00
25%,60000.00,1073338715.50,50000.00,33.74,-118.54,1183.00,59000.00,9.00,NaN,NaN,1073338715.50,250.00,2.00,0.12,1960.00,830.00,2.00,2023.00,1161.00,2.00,NaN,0.00,NaN,1.00,4941.00,1.00,1.00,0.00,5181.00,NaN,2.00
50%,639900.00,1093491199.00,629000.00,34.04,-118.04,1579.00,629500.00,22.00,NaN,NaN,1093491199.00,6370.00,2.00,0.17,1979.00,2895.00,2.00,2023.00,1700.00,3.00,NaN,0.00,NaN,1.00,7020.00,2.00,2.00,0.00,7280.00,NaN,2.50
75%,1089000.00,1114591744.50,1070000.00,34.31,-117.33,2150.00,1050000.00,53.00,NaN,NaN,1114591744.50,19495.50,3.00,0.30,1999.00,11063.00,3.00,2024.00,2650.00,4.00,NaN,0.00,NaN,2.00,11440.00,3.00,2.00,295.00,12870.00,NaN,2.50
max,1390000000.00,1156622452.00,989500000.00,157.00,329.00,909090909.00,137500000.00,12430.00,NaN,NaN,1156622452.00,10254000.00,2593669.00,370260000.00,2026.00,721271024.00,175.00,2026.00,462607.00,123.00,NaN,17424.00,NaN,2.00,918742280.00,3333.00,600.00,750000.00,5193920160.00,NaN,100000.00

In [8]:
merged_residential_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,382474.00,383191.00,383189.00,367472.00,367472.00,382965.00,383191.00,383191.00,0.00,0.00,383191.00,0.00,382765.00,352859.00,382843.00,382760.00,383122.00,0.00,26730.00,383180.00,0.00,2204.00,0.00,323525.00,353341.00,222074.00,366778.00,295086.00,353222.00,0.00,46125.00
mean,1227600.72,1093962732.16,1187453.68,34.66,-118.57,1905.41,1139544.97,36.99,NaN,NaN,1093962732.16,NaN,9.57,69.90,1978.51,10452.08,2.53,NaN,2118.50,3.20,NaN,99.87,NaN,1.36,38717.64,2.06,1.86,234.41,331360.15,NaN,221.93
std,6898043.12,28647177.27,5991397.04,1.71,2.98,27520.69,1355404.84,53.09,NaN,NaN,28647177.27,NaN,4192.42,16631.36,26.27,233043.30,1.14,NaN,1709.17,1.07,NaN,749.78,NaN,0.48,2179146.73,7.38,3.71,1804.91,16138626.84,NaN,2590.41
min,0.00,421678487.00,0.00,-117.47,-177.65,0.00,525.00,-288.00,NaN,NaN,421678487.00,NaN,-143.00,0.00,1776.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00
25%,585000.00,1073320944.50,575000.00,33.74,-118.89,1247.00,578000.00,8.00,NaN,NaN,1073320944.50,NaN,2.00,0.12,1960.00,1003.75,2.00,NaN,1270.00,3.00,NaN,0.00,NaN,1.00,5000.00,1.00,2.00,0.00,5227.00,NaN,2.00
50%,825000.00,1090593579.00,824480.00,34.05,-118.02,1640.00,817000.00,18.00,NaN,NaN,1090593579.00,NaN,2.00,0.17,1979.00,3289.50,2.00,NaN,1714.00,3.00,NaN,0.00,NaN,1.00,7013.00,2.00,2.00,95.00,7236.00,NaN,2.50
75%,1299000.00,1114319133.50,1300000.00,34.56,-117.27,2216.00,1295000.00,48.00,NaN,NaN,1114319133.50,NaN,3.00,0.27,1998.00,12001.00,3.00,NaN,2459.00,4.00,NaN,0.00,NaN,2.00,10890.00,3.00,2.00,366.00,11762.00,NaN,2.50
max,1390000000.00,1156622452.00,989500000.00,56.13,329.00,17021321.00,137500000.00,12430.00,NaN,NaN,1156622452.00,NaN,2593669.00,7810698.36,2026.00,78147816.00,175.00,NaN,123764.00,45.00,NaN,14531.00,NaN,2.00,918742280.00,3333.00,600.00,750000.00,2208317760.00,NaN,100000.00

In [9]:
print("rows in merged df: " + str(len(merged_df)))
print("rows in merged residential df: " + str(len(merged_residential_df)))
print("difference in rows: " + str(len(merged_df) - len(merged_residential_df)))

rows in merged df: 571143
rows in merged residential df: 383191
difference in rows: 187952

In [10]:
# merged_residential_df.to_csv("sold_merged_residential.csv", index=False)

Merged analysis

In [11]:
merged_df['PropertyType'].unique()

array(['Residential', 'CommercialLease', 'Land', 'ResidentialLease',
       'ManufacturedInPark', 'ResidentialIncome', 'CommercialSale',
       'BusinessOpportunity'], dtype=object)

In [12]:
nulls = merged_df.isnull().sum()

total_rows = len(merged_df)

useless_Residential_columns = []

for column, null_count in nulls.items():
    percentage = (null_count / total_rows)
    if percentage > .9:
        print(f"{column}: {percentage:.2%} null")
        useless_Residential_columns.append(column)

WaterfrontYN: 99.95% null
BasementYN: 98.35% null
FireplacesTotal: 100.00% null
AboveGradeFinishedArea: 100.00% null
TaxAnnualAmount: 99.57% null
BuilderName: 96.19% null
TaxYear: 99.94% null
ElementarySchoolDistrict: 100.00% null
CoBuyerAgentFirstName: 91.89% null
BelowGradeFinishedArea: 99.56% null
BusinessType: 99.72% null
CoveredSpaces: 100.00% null
LotSizeDimensions: 94.76% null
MiddleOrJuniorSchoolDistrict: 100.00% null
OriginatingSystemName: 92.99% null
OriginatingSystemSubName: 92.99% null

the columns with > 90% nulls were put into a list called "useless_Residential_columns"

In [13]:
Price_LivingArea_DOM_df = merged_df[['ClosePrice', 'LivingArea', 'DaysOnMarket']]
Price_LivingArea_DOM_df.describe()

        ClosePrice   LivingArea  DaysOnMarket
count    571136.00    530848.00     571143.00
mean     874306.98      3555.48         42.91
std     5289874.38   1247951.44         69.56
min           0.00         0.00       -288.00
25%       50000.00      1183.00          9.00
50%      629000.00      1579.00         22.00
75%     1070000.00      2150.00         53.00
max   989500000.00 909090909.00      12430.00

In [14]:
# Price_LivingArea_DOM_df.to_csv("Price_LivingArea_DOM_sold.csv", index=False)

FRED Analysis

In [15]:
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"
mortgage = pd.read_csv(url, parse_dates=['observation_date'])
mortgage = mortgage[mortgage['observation_date'] >= '2024-01-01'].reset_index().drop(columns=['index'])
mortgage.columns = ['date', 'rate_30yr_fixed']

In [16]:
mortgage.head()

        date  rate_30yr_fixed
0 2024-01-04             6.62
1 2024-01-11             6.66
2 2024-01-18             6.60
3 2024-01-25             6.69
4 2024-02-01             6.63

In [17]:
mortgage['year_month'] = mortgage['date'].dt.to_period('M')
mortgage_monthly = (
 mortgage.groupby('year_month')['rate_30yr_fixed']
 .mean()
 .reset_index()
)
mortgage_monthly.head()

  year_month  rate_30yr_fixed
0    2024-01             6.64
1    2024-02             6.78
2    2024-03             6.82
3    2024-04             6.99
4    2024-05             7.06

In [18]:
sold = merged_df
sold['year_month'] = pd.to_datetime(sold['CloseDate']).dt.to_period('M')
sold[['CloseDate', 'year_month']].head()

    CloseDate year_month
0  2024-01-26    2024-01
1  2024-01-24    2024-01
2  2024-01-16    2024-01
3  2024-01-08    2024-01
4  2024-01-17    2024-01

In [19]:
sold_with_rates = sold.merge(mortgage_monthly, on='year_month', how='left')
print(sold_with_rates['rate_30yr_fixed'].isnull().sum())

0

In [20]:
sold_with_rates[
    ['CloseDate', 'year_month', 'ClosePrice', 'rate_30yr_fixed']
].head()

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01   240000.00             6.64
1  2024-01-24    2024-01      950.00             6.64
2  2024-01-16    2024-01    45000.00             6.64
3  2024-01-08    2024-01   141500.00             6.64
4  2024-01-17    2024-01    15000.00             6.64

In [21]:
sold_with_rates[
    ['CloseDate', 'year_month', 'ClosePrice', 'rate_30yr_fixed']
].drop_duplicates('year_month').head(100)

         CloseDate year_month  ClosePrice  rate_30yr_fixed
0       2024-01-26    2024-01   240000.00             6.64
17976   2024-02-07    2024-02  1249000.00             6.78
37901   2024-03-19    2024-03    12000.00             6.82
61177   2024-04-29    2024-04    45000.00             6.99
85817   2024-05-31    2024-05  2900000.00             7.06
112304  2024-06-25    2024-06     1250.00             6.92
136632  2024-07-15    2024-07     4105.00             6.85
162872  2024-08-22    2024-08        1.50             6.50
187430  2024-09-12    2024-09  1090000.00             6.18
208697  2024-10-01    2024-10  5000000.00             6.43
231971  2024-11-10    2024-11     1940.00             6.80
252250  2024-12-13    2024-12  2100000.00             6.71
272491  2025-01-13    2025-01   442000.00             6.96
291229  2025-02-21    2025-02    35000.00             6.84
309931  2025-03-19    2025-03     3550.00             6.65
331376  2025-04-01    2025-04     2995.00             6.72
354638  2025-05-27    2025-05        2.00             6.82
377792  2025-06-26    2025-06     3995.00             6.82
400675  2025-07-24    2025-07     6300.00             6.72
424321  2025-08-11    2025-08   150000.00             6.59
447293  2025-09-26    2025-09    35000.00             6.35
469736  2025-10-22    2025-10        1.51             6.25
492969  2025-11-30    2025-11  1250000.00             6.24
512057  2025-12-31    2025-12  1998000.00             6.19
532595  2026-01-02    2026-01 11706000.00             6.10
549082  2026-02-19    2026-02  1580000.00             6.05
568143  2026-03-31    2026-03  1240000.00             6.18

In [22]:
# sold_with_rates.to_csv(/week 2-3/FRED_rates_sold.csv', index=False)

Data Cleaning

In [23]:
merged_df = pd.read_csv('week 2-3\FRED_rates_sold.csv', encoding='latin-1')
merged_df = merged_df.drop(columns=useless_Residential_columns)
print(len(merged_df))

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_23868\284231277.py:1: DtypeWarning: Columns (0,1,9,64,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv('week 2-3\FRED_rates_sold.csv', encoding='latin-1')

397603

In [24]:
date_fields = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
for field in date_fields:
    merged_df[field] = pd.to_datetime(merged_df[field])

print(merged_df.isnull().sum())

BuyerAgentAOR                   49091
ListAgentAOR                    46186
Flooring                       142590
ViewYN                          33869
PoolPrivateYN                   34435
OriginalListPrice                 721
ListingKey                          0
ListAgentEmail                  29012
CloseDate                           0
ClosePrice                          2
ListAgentFirstName               2999
ListAgentLastName                  40
Latitude                        15822
Longitude                       15822
UnparsedAddress                   362
PropertyType                        0
LivingArea                        229
ListPrice                           0
DaysOnMarket                        0
ListOfficeName                      0
BuyerOfficeName                  6538
CoListOfficeName               303521
ListAgentFullName                  85
CoListAgentFirstName           306611
CoListAgentLastName            306376
BuyerAgentMlsId                   503
BuyerAgentFirstName              1952
BuyerAgentLastName                167
AssociationFeeFrequency        232049
ListingKeyNumeric                   0
MLSAreaMajor                    53122
CountyOrParish                      0
MlsStatus                           0
ElementarySchool               344627
AttachedGarageYN                60679
ParkingTotal                      426
PropertySubType                   776
LotSizeAcres                    31364
SubdivisionName                249875
BuyerOfficeAOR                  21446
YearBuilt                         356
StreetNumberNumeric               445
ListingId                           0
BathroomsTotalInteger              69
City                              310
BuildingAreaTotal              369810
BedroomsTotal                      11
ContractStatusChangeDate          589
PurchaseContractDate              194
ListingContractDate                 1
StateOrProvince                     0
MiddleOrJuniorSchool           344273
FireplaceYN                       316
Stories                         61503
HighSchool                     328353
Levels                          38569
LotSizeArea                     30863
MainLevelBedrooms              166841
NewConstructionYN               29453
GarageSpaces                    17053
HighSchoolDistrict             108857
PostalCode                          2
AssociationFee                  90998
LotSizeSquareFeet               30987
BuyerAgencyCompensationType    351467
BuyerAgencyCompensation        351478
latfilled                      333719
lonfilled                      333719
year_month                          0
rate_30yr_fixed                     0
dtype: int64

In [25]:
print(merged_df.dtypes)

BuyerAgentAOR                          object
ListAgentAOR                           object
Flooring                               object
ViewYN                                 object
PoolPrivateYN                          object
OriginalListPrice                     float64
ListingKey                              int64
ListAgentEmail                         object
CloseDate                      datetime64[ns]
ClosePrice                            float64
ListAgentFirstName                     object
ListAgentLastName                      object
Latitude                              float64
Longitude                             float64
UnparsedAddress                        object
PropertyType                           object
LivingArea                            float64
ListPrice                             float64
DaysOnMarket                            int64
ListOfficeName                         object
BuyerOfficeName                        object
CoListOfficeName                       object
ListAgentFullName                      object
CoListAgentFirstName                   object
CoListAgentLastName                    object
BuyerAgentMlsId                        object
BuyerAgentFirstName                    object
BuyerAgentLastName                     object
AssociationFeeFrequency                object
ListingKeyNumeric                       int64
MLSAreaMajor                           object
CountyOrParish                         object
MlsStatus                              object
ElementarySchool                       object
AttachedGarageYN                       object
ParkingTotal                          float64
PropertySubType                        object
LotSizeAcres                          float64
SubdivisionName                        object
BuyerOfficeAOR                         object
YearBuilt                             float64
StreetNumberNumeric                   float64
ListingId                              object
BathroomsTotalInteger                 float64
City                                   object
BuildingAreaTotal                     float64
BedroomsTotal                         float64
ContractStatusChangeDate       datetime64[ns]
PurchaseContractDate           datetime64[ns]
ListingContractDate            datetime64[ns]
StateOrProvince                        object
MiddleOrJuniorSchool                   object
FireplaceYN                            object
Stories                               float64
HighSchool                             object
Levels                                 object
LotSizeArea                           float64
MainLevelBedrooms                     float64
NewConstructionYN                      object
GarageSpaces                          float64
HighSchoolDistrict                     object
PostalCode                             object
AssociationFee                        float64
LotSizeSquareFeet                     float64
BuyerAgencyCompensationType            object
BuyerAgencyCompensation               float64
latfilled                              object
lonfilled                              object
year_month                             object
rate_30yr_fixed                       float64
dtype: object

In [26]:
obj_cols = merged_df.select_dtypes(include='object').columns
numeric_cols = []
# find all object columns that can be converted to numeric, excluding boolean columns
for col in obj_cols:
    if 'Name' in col:
            continue
    if merged_df[col].dropna().map(type).eq(bool).any():
        continue
    converted = pd.to_numeric(merged_df[col], errors='coerce')
    if converted.notnull().sum() > 0:
        numeric_cols.append(col)
print(f"Object columns that can be converted to numeric: {numeric_cols}")

Object columns that can be converted to numeric: ['BuyerAgentMlsId', 'ListingId', 'PostalCode']

In [27]:
merged_df[numeric_cols] = merged_df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [28]:
num_cols = merged_df.select_dtypes(include=['number']).columns
merged_df[num_cols] = merged_df[num_cols].fillna(0)

date_cols = merged_df.select_dtypes(include=['datetime64']).columns
merged_df[date_cols] = merged_df[date_cols].fillna(pd.NaT)

obj_cols = merged_df.select_dtypes(include=['object']).columns
merged_df[obj_cols] = merged_df[obj_cols].fillna('Unknown')

print(merged_df.isnull().sum())

BuyerAgentAOR                    0
ListAgentAOR                     0
Flooring                         0
ViewYN                           0
PoolPrivateYN                    0
OriginalListPrice                0
ListingKey                       0
ListAgentEmail                   0
CloseDate                        0
ClosePrice                       0
ListAgentFirstName               0
ListAgentLastName                0
Latitude                         0
Longitude                        0
UnparsedAddress                  0
PropertyType                     0
LivingArea                       0
ListPrice                        0
DaysOnMarket                     0
ListOfficeName                   0
BuyerOfficeName                  0
CoListOfficeName                 0
ListAgentFullName                0
CoListAgentFirstName             0
CoListAgentLastName              0
BuyerAgentMlsId                  0
BuyerAgentFirstName              0
BuyerAgentLastName               0
AssociationFeeFrequency          0
ListingKeyNumeric                0
MLSAreaMajor                     0
CountyOrParish                   0
MlsStatus                        0
ElementarySchool                 0
AttachedGarageYN                 0
ParkingTotal                     0
PropertySubType                  0
LotSizeAcres                     0
SubdivisionName                  0
BuyerOfficeAOR                   0
YearBuilt                        0
StreetNumberNumeric              0
ListingId                        0
BathroomsTotalInteger            0
City                             0
BuildingAreaTotal                0
BedroomsTotal                    0
ContractStatusChangeDate       589
PurchaseContractDate           194
ListingContractDate              1
StateOrProvince                  0
MiddleOrJuniorSchool             0
FireplaceYN                      0
Stories                          0
HighSchool                       0
Levels                           0
LotSizeArea                      0
MainLevelBedrooms                0
NewConstructionYN                0
GarageSpaces                     0
HighSchoolDistrict               0
PostalCode                       0
AssociationFee                   0
LotSizeSquareFeet                0
BuyerAgencyCompensationType      0
BuyerAgencyCompensation          0
latfilled                        0
lonfilled                        0
year_month                       0
rate_30yr_fixed                  0
dtype: int64

In [29]:
merged_df.describe()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,BuyerAgentMlsId,ListingKeyNumeric,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,ListingId,BathroomsTotalInteger,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,PurchaseContractDate,ListingContractDate,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,PostalCode,AssociationFee,LotSizeSquareFeet,BuyerAgencyCompensation,rate_30yr_fixed
count,397603.00,397603.00,397603,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397014,397409,397602,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00,397603.00
mean,1222515.81,1095907674.82,2025-02-05 13:49:35.020812288,1185610.40,33.27,-113.85,1903.25,1138630.30,37.34,46059.91,1095907674.82,9.32,63.15,1976.80,10429.50,8926550.22,2.53,148.09,3.20,2025-02-06 03:47:12.220526592,2025-01-04 22:16:59.952744704,2024-11-20 19:37:23.161754112,1.15,35412.79,1.20,1.78,92083.50,181.10,308627.73,25.75,6.61
min,0.00,421678487.00,2024-01-01 00:00:00,0.00,-117.47,-177.65,0.00,525.00,-288.00,0.00,421678487.00,-143.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2024-01-01 00:00:00,1923-11-16 00:00:00,1984-08-28 00:00:00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.05
25%,585000.00,1075071090.50,2024-07-12 00:00:00,575000.00,33.70,-118.75,1246.00,575000.00,8.00,0.00,1075071090.50,2.00,0.11,1960.00,1002.00,0.00,2.00,0.00,3.00,2024-07-15 00:00:00,2024-06-12 00:00:00,2024-05-07 00:00:00,1.00,4012.00,0.00,1.00,91746.00,0.00,4600.00,0.00,6.35
50%,825000.00,1093954124.00,2025-02-06 00:00:00,820000.00,34.02,-117.96,1640.00,815000.00,19.00,0.00,1093954124.00,2.00,0.16,1979.00,3286.00,0.00,2.00,0.00,3.00,2025-02-06 00:00:00,2025-01-06 00:00:00,2024-11-07 00:00:00,1.00,6700.00,0.00,2.00,92373.00,0.00,6969.60,0.00,6.72
75%,1299000.00,1115093965.50,2025-08-25 00:00:00,1300000.00,34.49,-117.23,2217.00,1295000.00,48.00,0.00,1115093965.50,3.00,0.25,1999.00,12016.00,0.00,3.00,0.00,4.00,2025-08-25 00:00:00,2025-07-25 00:00:00,2025-06-04 00:00:00,2.00,10200.00,2.00,2.00,93420.00,289.11,10906.00,0.00,6.82
max,1390000000.00,1157158772.00,2026-03-31 00:00:00,989500000.00,56.13,329.00,17021321.00,137500000.00,12430.00,365199873.00,1157158772.00,2593669.00,7810698.36,2026.00,78147816.00,226001250.00,175.00,123764.00,45.00,2026-03-31 00:00:00,2026-03-31 00:00:00,2026-03-31 00:00:00,2.00,918742280.00,3333.00,600.00,980803.00,750000.00,2208317760.00,100000.00,7.06
std,6773854.31,29934582.73,NaN,5922366.11,6.98,23.36,27010.07,1353707.09,53.54,2771038.51,29934582.73,4113.45,15670.05,64.74,228674.46,28648885.41,1.14,703.51,1.07,NaN,NaN,NaN,0.66,2055034.44,5.61,3.65,7101.56,1559.46,15658656.92,885.14,0.29

In [30]:
cols_to_check = ['ClosePrice', 'LivingArea']
for col in cols_to_check:
    merged_df = merged_df[merged_df[col] > 0]

cols_to_check = ['DaysOnMarket', 'BedroomsTotal', 'BathroomsTotalInteger']
for col in cols_to_check:
    merged_df = merged_df[merged_df[col] >= 0]

In [31]:
#ListingContractDate after CloseDate
merged_df['listing_after_close_flag'] = merged_df['ListingContractDate'] > merged_df['CloseDate']

#PurchaseContractDate after CloseDate
merged_df['purchase_after_close_flag'] = merged_df['PurchaseContractDate'] > merged_df['CloseDate']

# timeline is out of order (listing -> purchase -> close)
merged_df['negative_timeline_flag'] = (
    (merged_df['ListingContractDate'] > merged_df['PurchaseContractDate']) |
    (merged_df['PurchaseContractDate'] > merged_df['CloseDate'])
)

In [32]:
#double check if there are lingering nulls in longitude or latitude
merged_df['nullCoordsFlag'] = merged_df['Longitude'].isnull() | merged_df['Latitude'].isnull()
#estates with zeros in either longitude or latitude
merged_df['zeroCoordsFlag'] = (merged_df['Longitude'] == 0) | (merged_df['Latitude'] == 0)
#these estates are within CA
merged_df['positive_longitude_flag'] = merged_df['Longitude'] > 0

# California bounding box (approximate)
CA_LAT_MIN, CA_LAT_MAX = 32.5, 42.0
CA_LON_MIN, CA_LON_MAX = -124.5, -114.0

# Flag coordinates outside California's bounding box
merged_df['out_of_state_flag'] = ~(
    (merged_df['Latitude'].between(CA_LAT_MIN, CA_LAT_MAX)) &
    (merged_df['Longitude'].between(CA_LON_MIN, CA_LON_MAX))
)

merged_df[['Longitude', 'Latitude', 'nullCoordsFlag', 'zeroCoordsFlag', 'out_of_state_flag']].head(20)

    Longitude  Latitude  nullCoordsFlag  zeroCoordsFlag  out_of_state_flag
0        0.00      0.00           False            True               True
1        0.00      0.00           False            True               True
2        0.00      0.00           False            True               True
3        0.00      0.00           False            True               True
4     -118.56     34.16           False           False              False
5     -120.65     35.28           False           False              False
7        0.00      0.00           False            True               True
8     -117.17     32.72           False           False              False
9     -118.26     34.07           False           False              False
10    -118.22     34.11           False           False              False
11       0.00      0.00           False            True               True
12       0.00      0.00           False            True               True
13    -117.64     33.68           False           False              False
14       0.00      0.00           False            True               True
15    -118.63     34.47           False           False              False
16    -117.23     33.37           False           False              False
17    -118.32     33.87           False           False              False
18    -118.27     34.25           False           False              False
19    -116.70     32.75           False           False              False
20       0.00      0.00           False            True               True

In [33]:
print('data cleaning summary:')
print('started with 397603 rows')
print(f'ended with {len(merged_df)} rows')
print(f'difference of {397603 - len(merged_df)}')
nullCordsCount = (merged_df['nullCoordsFlag'] == True).sum()
zeroCoordsCount = (merged_df['zeroCoordsFlag'] == True).sum()
out_of_state_count = (merged_df['out_of_state_flag'] == True).sum()
print()
print(f'null coordinates count: {nullCordsCount}')
print(f'zero coordinates count: {zeroCoordsCount}')
print(f'out of state coordinates count: {out_of_state_count}')
print(f'total flags count: {nullCordsCount + zeroCoordsCount + out_of_state_count}')

data cleaning summary:
started with 397603 rows
ended with 397181 rows
difference of 422

null coordinates count: 0
zero coordinates count: 15846
out of state coordinates count: 15906
total flags count: 31752

In [ ]:
#merged_df.to_csv("cleaned_sold_data.csv", index=False)