In [3]:
import pandas as pd
import os

pd.options.display.float_format = '{:1.2f}'.format
pd.options.display.max_columns = None

In [4]:
files = 0
for file in os.listdir("raw_listing"):
    files += 1
print(f"Number of listing files: {files}")

Number of listing files: 27

In [5]:
df = pd.read_csv(f"raw_listing/CRMLSListing202502.csv", encoding='latin-1')

print('listing data:')
df.head()

listing data:

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,PropertyType.1,MlsStatus,ElementarySchool,ListAgentFirstName.1,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,Longitude.1,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,Latitude.1,ListPrice.1,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,ListAgentLastName.1,CloseDate.1,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1100000.00,1108426966,Andrew.Liberty@compass.com,NaN,NaN,Andrew R.,Liberty,34.11,-118.25,3170 Larga Avenue,ResidentialIncome,1196.00,1100000.00,29,Compass,NaN,"Secret HQ, Inc",Andrew R. Liberty,Lek,Adjchavanich,NaN,NaN,NaN,NaN,NaN,NaN,1108426966,606 - Atwater,NaN,Los Angeles,ResidentialIncome,Active,NaN,Andrew R.,False,0.00,NaN,NaN,0.12,NaN,NaN,1928.00,29,3170.00,1196.00,25508805,2.00,Los Angeles,NaN,1196.00,2.00,2025-02-07,-118.25,NaN,NaN,NaN,2025-02-07,NaN,NaN,34.11,1100000.00,CA,NaN,NaN,NaN,NaN,NaN,MultiSplit,Liberty,NaN,NaN,5413.00,NaN,False,NaN,NaN,90039,NaN,NaN,5413.00,NaN,3170 Larga Avenue
1,595500.00,1108426965,williamramsey760@gmail.com,NaN,NaN,William,Ramsey,34.18,-116.07,72772 Nandina Street,Residential,1712.00,595500.00,0,"Sharon Rose Realty, Inc.",NaN,"Sharon Rose Realty, Inc.",William Ramsey,Luis,Carrillo,NaN,NaN,NaN,NaN,NaN,NaN,1108426965,DC710 - Desert Heights,NaN,San Bernardino,Residential,Active,NaN,William,True,2.00,NaN,SingleFamilyResidence,2.27,Not Applicable-1,NaN,2006.00,0,72772.00,1712.00,219126159PS,2.00,29 Palms,NaN,NaN,3.00,2025-02-25,-116.07,NaN,NaN,NaN,2025-02-25,NaN,NaN,34.18,595500.00,CA,NaN,NaN,True,1.00,NaN,One,Ramsey,NaN,NaN,99011.00,NaN,False,2.00,NaN,92277,NaN,NaN,99011.00,NaN,72772 Nandina Street
2,3500.00,1108426536,omegafunding@yahoo.com,NaN,NaN,Vartan,Missirian,34.13,-117.91,300 N San Gabriel Avenue,ResidentialLease,1380.00,3500.00,0,Legend Realtors,NaN,Legend Realtors,Vartan Missirian,Alina,Missirian,NaN,NaN,NaN,NaN,NaN,NaN,1108426536,607 - Azusa,NaN,Los Angeles,ResidentialLease,Active,NaN,Vartan,NaN,1.00,NaN,Duplex,6900.00,Not Applicable,NaN,1989.00,0,300.00,1380.00,P1-21172,2.00,Azusa,NaN,NaN,3.00,2025-02-27,-117.91,NaN,NaN,NaN,2025-02-27,NaN,NaN,34.13,3500.00,CA,NaN,NaN,True,1.00,NaN,One,Missirian,NaN,NaN,6900.00,3.00,NaN,0.00,NaN,91702,NaN,0.00,300564000.00,NaN,300 N San Gabriel Avenue
3,995000.00,1108426334,Jessica@native.us,NaN,NaN,Jessica,Foote,33.61,-117.19,26891 Aubrieta Street,Residential,3863.00,995000.00,0,Native,NaN,Native,Jessica Foote,Reanne,Mosley,NaN,NaN,NaN,NaN,Monthly,NaN,1108426334,SRCAR - Southwest Riverside County,NaN,Riverside,Residential,Active,NaN,Jessica,True,6.00,NaN,SingleFamilyResidence,0.16,NaN,NaN,2005.00,0,26891.00,3863.00,SW25044469,5.00,Murrieta,NaN,NaN,4.00,2025-02-26,-117.19,NaN,NaN,NaN,2025-02-26,NaN,NaN,33.61,995000.00,CA,NaN,NaN,True,2.00,NaN,Two,Foote,NaN,NaN,6970.00,1.00,False,4.00,Murrieta,92562,NaN,227.00,6970.00,NaN,26891 Aubrieta Street
4,1485000.00,1108425215,nickiwanderson@gmail.com,NaN,NaN,Nicki,Anderson,35.14,-120.56,608 Stagecoach,Residential,2411.00,1485000.00,0,Comet Realty,NaN,Comet Realty,Nicki Anderson,Brian,Gust,NaN,NaN,NaN,NaN,Monthly,NaN,1108425215,AG-East of Hwy 101,NaN,San Luis Obispo,Residential,Active,Branch,Nicki,True,3.00,Midland Pacific,SingleFamilyResidence,0.47,NaN,NaN,2001.00,0,608.00,2411.00,PI25050653,3.00,Arroyo Grande,NaN,NaN,3.00,2025-02-27,-120.56,NaN,NaN,NaN,2025-02-27,NaN,NaN,35.14,1485000.00,CA,NaN,NaN,True,NaN,NaN,MultiSplit,Anderson,NaN,NaN,0.47,1.00,False,3.00,Lucia Mar Unified,93420,NaN,72.00,20473.20,NaN,608 Stagecoach

In [6]:
df.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'StreetNumberNumeric', 'LivingArea.1', 'ListingId',
       'BathroomsTotalInteger', 'City', 'TaxYear', 'BuildingAreaTotal',
       'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince',
       'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories',
       'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1',
       'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [7]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,Longitude.1,ElementarySchoolDistrict,BelowGradeFinishedArea,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,33853.00,33983.00,2725.00,33500.00,33525.00,29545.00,33888.00,33983.00,0.00,0.00,33983.00,236.00,31870.00,30895.00,31076.00,33983.00,33810.00,29545.00,31126.00,31.00,5676.00,29685.00,33525.00,0.00,131.00,33500.00,33888.00,0.00,24478.00,31013.00,14738.00,27270.00,22816.00,30980.00,0.00
mean,1183687.39,1106732686.86,652947.85,34.65,-118.49,1955.01,1096204.91,9.43,NaN,NaN,1106732686.86,14472.10,2.64,27.40,1978.47,9.43,22895.72,1955.01,2.54,2023.97,3269.62,3.16,-118.49,NaN,99.94,34.65,1096204.91,NaN,1.37,56327.24,1.93,1.73,218.33,382129.32,NaN
std,8334258.54,1441429.97,1299081.75,1.75,5.03,1555.52,2500914.67,12.87,NaN,NaN,1441429.97,21595.08,8.46,2485.39,28.42,12.87,734313.50,1555.52,1.75,0.60,7827.51,1.70,5.03,NaN,357.64,1.75,2500914.67,NaN,0.48,966143.39,1.48,2.78,525.80,19456004.96,NaN
min,0.19,1054004728.00,480.00,-41.28,-123.84,0.00,0.19,-6.00,NaN,NaN,1054004728.00,0.00,-30.00,0.00,1776.00,-6.00,0.00,0.00,0.00,2022.00,0.00,0.00,-123.84,NaN,0.00,-41.28,0.19,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,157500.00,1106466326.50,3645.00,33.76,-118.66,1191.00,159000.00,3.00,NaN,NaN,1106466326.50,305.25,1.00,0.12,1959.00,3.00,761.00,1191.00,2.00,2024.00,1253.00,2.00,-118.66,NaN,0.00,33.76,159000.00,NaN,1.00,5000.00,1.00,1.00,0.00,5250.00,NaN
50%,674999.00,1107234029.00,8000.00,34.07,-118.14,1622.00,674000.00,8.00,NaN,NaN,1107234029.00,7999.00,2.00,0.17,1979.00,8.00,2742.00,1622.00,2.00,2024.00,1953.00,3.00,-118.14,NaN,0.00,34.07,674000.00,NaN,1.00,7349.00,2.00,2.00,0.00,7502.00,NaN
75%,1250000.00,1107705449.50,940000.00,34.51,-117.29,2296.00,1250000.00,14.00,NaN,NaN,1107705449.50,21379.00,3.00,0.41,2001.00,14.00,10743.50,2296.00,3.00,2024.00,3392.50,4.00,-117.29,NaN,0.00,34.51,1250000.00,NaN,2.00,14785.00,3.00,2.00,345.00,17524.25,NaN
max,969000000.00,1108426966.00,32500000.00,43.88,329.00,84500.00,177000000.00,1101.00,NaN,NaN,1108426966.00,225597.00,650.00,414293.00,2028.00,1101.00,61517416.00,84500.00,57.00,2025.00,449040.00,78.00,329.00,NaN,2300.00,43.88,177000000.00,NaN,2.00,117432626.96,33.00,400.00,26896.00,2087220960.00,NaN

In [10]:
merged_df = None
folder_path = "raw_listing"
for file in os.listdir(folder_path):
    df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
    Residential_df = df[df['PropertyType'] == 'Residential']
    if merged_df is None:
        merged_df = df
        merged_residential_df = Residential_df
    else:
        merged_df = pd.concat([merged_df, df])
        merged_residential_df = pd.concat([merged_residential_df, Residential_df])

In [11]:
merged_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,BathroomsTotalInteger,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,Longitude.1,ElementarySchoolDistrict,BelowGradeFinishedArea,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,849641.00,852963.00,239043.00,741053.00,741756.00,746485.00,850826.00,852963.00,0.00,0.00,852963.00,6072.00,800581.00,771538.00,783489.00,852963.00,849223.00,746485.00,782985.00,123519.00,869.00,136653.00,749881.00,741756.00,0.00,3426.00,741053.00,850826.00,0.00,632048.00,775317.00,395045.00,691074.00,577720.00,774240.00,0.00
mean,1050528.89,1104976762.58,784176.72,34.52,-118.36,3160.82,983334.34,19.51,NaN,NaN,1104976762.58,30660.17,6.44,551.07,1978.41,19.51,28219.06,3160.82,2.50,175.05,2023.33,3342.15,3.13,-118.36,NaN,96.76,34.52,983334.34,NaN,1.37,66426.01,1.93,1.76,205.12,562127.04,NaN
std,6391364.92,29955382.59,3418229.08,1.88,3.91,1052385.32,2163150.61,28.92,NaN,NaN,29955382.59,967227.93,2908.37,421673.86,28.04,28.92,2042718.07,1052385.32,3.04,2053.69,2.65,11311.33,1.69,3.91,NaN,497.11,1.88,2163150.61,NaN,0.48,2374153.17,5.60,3.94,2060.98,23101197.27,NaN
min,0.00,421654881.00,0.00,-117.47,-159.52,0.00,0.00,-58.00,NaN,NaN,421654881.00,0.00,-143.00,0.00,1776.00,-58.00,0.00,0.00,0.00,0.00,2004.00,0.00,0.00,-159.52,NaN,0.00,-117.47,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,85000.00,1077478681.50,5000.00,33.76,-118.51,1182.00,85000.00,4.00,NaN,NaN,1077478681.50,118.89,1.00,0.12,1960.00,4.00,765.00,1182.00,2.00,2.00,2023.00,1219.00,2.00,-118.51,NaN,0.00,33.76,85000.00,NaN,1.00,4935.00,1.00,1.00,0.00,5227.00,NaN
50%,639888.00,1104356715.00,570000.00,34.05,-118.09,1602.00,635000.00,10.00,NaN,NaN,1104356715.00,6250.00,2.00,0.17,1979.00,10.00,2760.00,1602.00,2.00,2.50,2024.00,1870.00,3.00,-118.09,NaN,0.00,34.05,635000.00,NaN,1.00,7228.00,2.00,2.00,0.00,7500.00,NaN
75%,1150000.00,1127370000.50,1030000.00,34.30,-117.29,2236.00,1150000.00,23.00,NaN,NaN,1127370000.50,19623.25,3.00,0.39,2001.00,23.00,10815.00,2236.00,3.00,2.50,2024.00,3211.00,4.00,-117.29,NaN,0.00,34.30,1150000.00,NaN,2.00,13695.00,3.00,2.00,310.00,16579.00,NaN
max,1390000000.00,1157177805.00,820000000.00,737.00,392.00,909090909.00,443650265.00,2539.00,NaN,NaN,1157177805.00,74460000.00,2593669.00,370260000.00,2028.00,2539.00,721271024.00,909090909.00,2208.00,200000.00,2026.00,1200000.00,149.00,392.00,NaN,17424.00,737.00,443650265.00,NaN,2.00,918742280.00,3333.00,600.00,968348.00,7638115320.00,NaN

In [12]:
merged_residential_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,BathroomsTotalInteger,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,Longitude.1,ElementarySchoolDistrict,BelowGradeFinishedArea,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,539409.00,540183.00,145580.00,460038.00,460038.00,539627.00,540183.00,540183.00,0.00,0.00,540183.00,0.00,540163.00,495665.00,539244.00,540183.00,539333.00,539627.00,540128.00,78993.00,0.00,47997.00,540035.00,460038.00,0.00,3029.00,460038.00,540183.00,0.00,445934.00,496504.00,294108.00,510192.00,410521.00,496329.00,0.00
mean,1397125.34,1104798805.71,1202136.39,34.60,-118.46,1980.06,1312996.78,19.54,NaN,NaN,1104798805.71,NaN,7.62,65.24,1979.60,19.54,11533.52,1980.06,2.63,189.11,NaN,2445.25,3.22,-118.46,NaN,87.07,34.60,1312996.78,NaN,1.37,46953.52,2.05,1.85,270.78,411030.33,NaN
std,7357158.89,29883843.49,4292685.77,2.00,3.60,23382.69,2346687.07,26.77,NaN,NaN,29883843.49,NaN,3529.17,12136.81,26.99,26.77,281856.83,23382.69,3.26,2340.72,NaN,2249.24,1.19,3.60,NaN,360.16,2.00,2346687.07,NaN,0.48,2178789.61,6.44,3.88,2369.07,20803367.94,NaN
min,0.00,1018357250.00,525.00,-117.47,-159.48,0.00,100.00,-58.00,NaN,NaN,1018357250.00,NaN,-143.00,0.00,1776.00,-58.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,-159.48,NaN,0.00,-117.47,100.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,585000.00,1077378664.50,600000.00,33.74,-118.68,1247.00,580000.00,5.00,NaN,NaN,1077378664.50,NaN,2.00,0.12,1961.00,5.00,975.00,1247.00,2.00,2.00,NaN,1305.00,2.00,-118.68,NaN,0.00,33.74,580000.00,NaN,1.00,5000.00,1.00,1.00,0.00,5227.00,NaN
50%,849000.00,1104806266.00,855000.00,34.05,-118.03,1669.00,840000.00,11.00,NaN,NaN,1104806266.00,NaN,2.00,0.17,1980.00,11.00,3271.00,1669.00,2.00,2.50,NaN,1824.00,3.00,-118.03,NaN,0.00,34.05,840000.00,NaN,1.00,7196.00,2.00,2.00,125.00,7405.00,NaN
75%,1389000.00,1126880009.50,1350000.00,34.47,-117.24,2300.00,1375000.00,23.00,NaN,NaN,1126880009.50,NaN,3.00,0.31,2001.00,23.00,12060.00,2300.00,3.00,2.50,NaN,2800.00,4.00,-117.24,NaN,0.00,34.47,1375000.00,NaN,2.00,12051.00,3.00,2.00,400.00,13615.00,NaN
max,1390000000.00,1157177805.00,820000000.00,737.00,329.00,17021321.00,195000000.00,731.00,NaN,NaN,1157177805.00,NaN,2593669.00,4187292.00,2028.00,731.00,79547958.00,17021321.00,2208.00,200000.00,NaN,123764.00,94.00,329.00,NaN,5000.00,737.00,195000000.00,NaN,2.00,918742280.00,3333.00,600.00,968348.00,7638115320.00,NaN

In [13]:
print("rows in merged df: " + str(len(merged_df)))
print("rows in merged residential df: " + str(len(merged_residential_df)))
print("difference in rows: " + str(len(merged_df) - len(merged_residential_df)))

rows in merged df: 852963
rows in merged residential df: 540183
difference in rows: 312780

In [ ]:
# merged_residential_df.to_csv("listing_merged_residential.csv", index=False)