In [1]:
import pandas as pd
import os

pd.options.display.float_format = '{:1.2f}'.format
pd.options.display.max_columns = None

In [2]:
files = 0
for file in os.listdir("raw_sold"):
    files += 1
print(f"Number of sold files: {files}")

Number of sold files: 27

In [3]:
df_S = pd.read_csv(f"raw_sold/CRMLSSold202502.csv", encoding='latin-1')

print('sold data:')
df_S.head()

sold data:

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,MlsStatus,ElementarySchool,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,RanchoSoutheast,RanchoSoutheast,NaN,True,NaN,NaN,NaN,60000.00,526199946,cmark1018@yahoo.com,2025-02-21,35000.00,Chris,Mark,34.54,-117.27,0 Quantico Road,Land,NaN,35000.00,196,Far West Realty,KW Vision,NaN,Chris Mark,NaN,NaN,TRSUDAJAM,James,Sudarsono,NaN,NaN,NaN,526199946,APPV - Apple Valley,NaN,San Bernardino,Closed,NaN,NaN,NaN,NaN,NaN,0.64,NaN,TriCounties,NaN,0.00,RS21140713,NaN,Apple Valley,NaN,NaN,NaN,2025-02-21,NaN,NaN,2022-01-10,2021-06-28,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28000.00,NaN,False,NaN,NaN,92307,0.00,28000.00,NaN
1,InlandValleys,InlandValleys,NaN,False,NaN,NaN,NaN,550000.00,525585060,mozcorona@aol.com,2025-02-14,625000.00,MANUEL,ZAMORANO,33.94,-117.24,24255 Sunnymead Boulevard,Land,NaN,550000.00,1232,"KAREN PIERCE, BROKER","KAREN PIERCE, BROKER",NaN,MANUEL ZAMORANO,NaN,NaN,ivzamoman,MANUEL,ZAMORANO,NaN,NaN,NaN,525585060,259 - Moreno Valley,NaN,Riverside,Closed,NaN,NaN,NaN,NaN,NaN,0.91,NaN,InlandValleys,NaN,24255.00,IV21138689,NaN,Moreno Valley,NaN,NaN,NaN,2025-02-14,NaN,NaN,2024-11-08,2021-06-25,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39640.00,NaN,False,NaN,NaN,92553,0.00,39640.00,NaN
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,880000.00,497696903,lenskab@gmail.com,2025-02-11,875000.00,Lenska,Bracknell,32.77,-117.04,4750 Dana Dr,Residential,2340.00,880000.00,20,LENSKA Realty,Coldwell Banker West,NaN,Lenska Bracknell,NaN,NaN,809976,Sheetal,Gandhi,NaN,NaN,NaN,497696903,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,6.00,NaN,SingleFamilyResidence,NaN,La Mesa,PacificSouthwest,2021.00,4750.00,210000201,4.00,La Mesa,NaN,NaN,4.00,2025-02-11,NaN,NaN,2021-01-25,2021-01-05,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN
3,SanDiego,SanDiego,NaN,False,NaN,NaN,False,875000.00,497696407,lenskab@gmail.com,2025-02-14,875000.00,Lenska,Bracknell,32.77,-117.04,4740 Dana Dr,Residential,2165.00,875000.00,9,LENSKA Realty,LENSKA Realty,NaN,Lenska Bracknell,NaN,NaN,SAND-649841,Lenska,Bracknell,NaN,NaN,NaN,497696407,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,4.00,NaN,SingleFamilyResidence,NaN,La Mesa,SanDiego,2021.00,4740.00,210000200,4.00,La Mesa,NaN,NaN,5.00,2025-02-14,NaN,NaN,2021-01-14,2021-01-05,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,849000.00,486616176,lenskab@gmail.com,2025-02-18,849000.00,Lenska,Bracknell,32.77,-117.04,4730 Dana Dr,Residential,2158.00,849000.00,91,LENSKA Realty,Heritage Homes San Diego,NaN,Lenska Bracknell,NaN,NaN,SAND-693007,Jason,Piske,NaN,NaN,NaN,486616176,91942 - La Mesa,NaN,San Diego,Closed,NaN,True,4.00,NaN,SingleFamilyResidence,NaN,La Mesa,SanDiego,2021.00,4730.00,200049530,3.00,La Mesa,NaN,NaN,4.00,2025-02-18,NaN,NaN,2021-01-25,2020-10-22,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,NaN,NaN,False,2.00,NaN,91942,NaN,NaN,NaN

In [4]:
df_S.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict'],
      dtype='object')

In [5]:
df_S.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,18649.00,18702.00,18702.00,18696.00,18697.00,17369.00,18670.00,18702.00,0.00,0.00,18702.00,95.00,18094.00,16908.00,17876.00,18651.00,17820.00,11.00,2637.00,17432.00,0.00,79.00,0.00,14675.00,16963.00,9732.00,16123.00,12758.00,16948.00,0.00
mean,983409.52,1096709782.05,838350.89,34.55,-118.48,1806.42,835031.62,47.21,NaN,NaN,1096709782.05,11431.70,2.39,48.26,1978.40,18863.77,2.46,2021.91,2611.76,3.07,NaN,116.14,NaN,1.36,37851.82,1.92,1.75,198.77,478056.46,NaN
std,11296281.99,18672040.17,1460341.89,1.62,3.35,1116.07,1247063.04,76.34,NaN,NaN,18672040.17,14804.16,4.29,2875.39,27.28,651982.38,1.41,4.01,4239.67,1.40,NaN,710.06,NaN,0.48,606935.47,1.44,3.35,594.61,18889275.45,NaN
min,0.00,421653552.00,0.00,0.00,-123.81,0.00,350.00,-288.00,NaN,NaN,421653552.00,0.00,-3.00,0.00,1776.00,0.00,0.00,2010.00,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,13995.00,1093798834.50,12562.50,33.74,-118.56,1179.00,13862.50,8.00,NaN,NaN,1093798834.50,270.00,2.00,0.12,1960.00,816.00,2.00,2023.00,1196.00,2.00,NaN,0.00,NaN,1.00,4811.00,1.00,1.00,0.00,5097.00,NaN
50%,617471.00,1100882618.50,610000.00,34.04,-118.06,1576.00,607119.00,22.00,NaN,NaN,1100882618.50,4638.00,2.00,0.17,1979.00,2812.00,2.00,2023.00,1740.00,3.00,NaN,0.00,NaN,1.00,7020.00,2.00,2.00,0.00,7264.50,NaN
75%,1075000.00,1102985592.75,1068000.00,34.37,-117.33,2140.00,1050000.00,63.00,NaN,NaN,1102985592.75,19932.50,2.00,0.30,2000.00,10760.00,3.00,2023.00,2726.00,4.00,NaN,0.00,NaN,2.00,11700.00,3.00,2.00,305.00,12870.00,NaN
max,1390000000.00,1108121032.00,113811672.00,41.64,117.30,44194.00,39995000.00,2799.00,NaN,NaN,1108121032.00,65787.00,400.00,287060.00,2025.00,60119213.00,61.00,2025.00,113471.00,61.00,NaN,6104.00,NaN,2.00,67300000.00,32.00,400.00,46356.20,1821592080.00,NaN

In [6]:
merged_df = None
folder_path = "raw_sold"
for file in os.listdir(folder_path):
    df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
    Residential_df = df[df['PropertyType'] == 'Residential']
    if merged_df is None:
        merged_df = df
        merged_residential_df = Residential_df
    else:
        merged_df = pd.concat([merged_df, df])
        merged_residential_df = pd.concat([merged_residential_df, Residential_df])

C:\Users\Jamesb\AppData\Local\Temp\ipykernel_34724\429532400.py:4: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_34724\429532400.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')
C:\Users\Jamesb\AppData\Local\Temp\ipykernel_34724\429532400.py:4: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{folder_path}/{file}", encoding='latin-1')

In [7]:
merged_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,590013.00,591733.00,591726.00,572703.00,572875.00,549951.00,590823.00,591733.00,0.00,0.00,591733.00,2511.00,573049.00,535701.00,566783.00,590267.00,564309.00,368.00,76682.00,552324.00,0.00,2591.00,0.00,473288.00,537570.00,313909.00,515952.00,408289.00,537111.00,0.00,67780.00
mean,905987.16,1095954792.93,874014.73,34.53,-118.45,3495.37,839973.29,43.29,NaN,NaN,1095954792.93,18458.23,7.60,762.92,1978.10,20203.93,2.45,2022.97,2551.71,3.08,NaN,106.52,NaN,1.36,48147.23,1.93,1.77,185.40,469684.28,NaN,194.41
std,5742312.61,33286305.26,5229021.13,1.61,3.11,1226085.59,1275509.04,69.84,NaN,NaN,33286305.26,210397.30,3437.23,506069.44,27.09,1467236.18,1.42,2.43,5188.90,1.40,NaN,799.67,NaN,0.48,2236985.93,6.25,3.88,1632.81,20770386.44,NaN,2152.72
min,0.00,421449042.00,0.00,-117.47,-177.65,0.00,0.00,-288.00,NaN,NaN,421449042.00,0.00,-143.00,0.00,1776.00,0.00,0.00,2009.00,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00
25%,65000.00,1075092157.00,52500.00,33.74,-118.54,1183.00,62500.00,9.00,NaN,NaN,1075092157.00,244.50,2.00,0.12,1960.00,832.00,2.00,2023.00,1161.00,2.00,NaN,0.00,NaN,1.00,4941.00,1.00,1.00,0.00,5185.00,NaN,2.00
50%,639990.00,1095333166.00,629727.50,34.04,-118.04,1579.00,629900.00,22.00,NaN,NaN,1095333166.00,6330.00,2.00,0.17,1979.00,2903.00,2.00,2023.00,1699.00,3.00,NaN,0.00,NaN,1.00,7025.00,2.00,2.00,0.00,7291.00,NaN,2.50
75%,1089000.00,1117387087.00,1070000.00,34.30,-117.33,2150.00,1050000.00,54.00,NaN,NaN,1117387087.00,19425.00,3.00,0.30,1999.00,11104.50,3.00,2024.00,2650.75,4.00,NaN,0.00,NaN,2.00,11480.00,3.00,2.00,295.00,12958.00,NaN,2.50
max,1390000000.00,1157176313.00,989500000.00,157.00,329.00,909090909.00,137500000.00,12430.00,NaN,NaN,1157176313.00,10254000.00,2593669.00,370260000.00,2026.00,721271024.00,175.00,2026.00,462607.00,123.00,NaN,17424.00,NaN,2.00,918742280.00,3333.00,600.00,750000.00,5193920160.00,NaN,100000.00

In [8]:
merged_residential_df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation
count,396882.00,397603.00,397601.00,381781.00,381781.00,397374.00,397603.00,397603.00,0.00,0.00,397603.00,0.00,397177.00,366239.00,397247.00,397158.00,397534.00,0.00,27793.00,397592.00,0.00,2290.00,0.00,336100.00,366740.00,230762.00,380550.00,306605.00,366616.00,0.00,46125.00
mean,1224736.70,1095907674.82,1185616.36,34.65,-118.57,1904.35,1138630.30,37.34,NaN,NaN,1095907674.82,NaN,9.33,68.56,1978.57,10441.18,2.53,NaN,2118.51,3.20,NaN,98.00,NaN,1.36,38392.95,2.06,1.86,234.85,334713.47,NaN,221.93
std,6779803.84,29934582.73,5922380.41,1.71,2.96,27017.81,1353707.09,53.54,NaN,NaN,29934582.73,NaN,4115.66,16327.24,26.27,228802.27,1.14,NaN,1704.70,1.07,NaN,737.04,NaN,0.48,2139732.14,7.24,3.71,1772.30,16306717.36,NaN,2590.41
min,0.00,421678487.00,0.00,-117.47,-177.65,0.00,525.00,-288.00,NaN,NaN,421678487.00,NaN,-143.00,0.00,1776.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00
25%,585000.00,1075071090.50,575000.00,33.74,-118.88,1247.00,575000.00,8.00,NaN,NaN,1075071090.50,NaN,2.00,0.12,1960.00,1006.00,2.00,NaN,1270.00,3.00,NaN,0.00,NaN,1.00,5000.00,1.00,2.00,0.00,5227.00,NaN,2.00
50%,825000.00,1093954124.00,820000.00,34.05,-118.01,1641.00,815000.00,19.00,NaN,NaN,1093954124.00,NaN,2.00,0.17,1979.00,3301.00,2.00,NaN,1713.00,3.00,NaN,0.00,NaN,1.00,7016.00,2.00,2.00,95.00,7242.00,NaN,2.50
75%,1299000.00,1115093965.50,1300000.00,34.55,-117.27,2217.00,1295000.00,48.00,NaN,NaN,1115093965.50,NaN,3.00,0.27,1999.00,12027.75,3.00,NaN,2458.00,4.00,NaN,0.00,NaN,2.00,10890.00,3.00,2.00,369.00,11825.00,NaN,2.50
max,1390000000.00,1157158772.00,989500000.00,56.13,329.00,17021321.00,137500000.00,12430.00,NaN,NaN,1157158772.00,NaN,2593669.00,7810698.36,2026.00,78147816.00,175.00,NaN,123764.00,45.00,NaN,14531.00,NaN,2.00,918742280.00,3333.00,600.00,750000.00,2208317760.00,NaN,100000.00

In [9]:
print("rows in merged df: " + str(len(merged_df)))
print("rows in merged residential df: " + str(len(merged_residential_df)))
print("difference in rows: " + str(len(merged_df) - len(merged_residential_df)))

rows in merged df: 591733
rows in merged residential df: 397603
difference in rows: 194130

In [ ]:
# merged_residential_df.to_csv("sold_merged_residential.csv", index=False)